### ISSUE TITLE
Structs: Faltam argumentos nos seletores

### ISSUE THREAD

**Issue by pfvscheffer** [pfvscheffer/GeradorRacket#1]
exemplo:
estrutura: `(define-struct estrutura (arg))`
seletor: `(estrutura-arg e)`

**Comment by lm-rodrigues** [comment]
Corrigido. 

Exemplo:

(define-struct arvore (iD esq dir))
;; Elemento do conjunto Arvore.
;; (make-arvore 1iD 1esq 1dir) onde:
;; 1iD: Numero
;; 1esq: Arvore
;; 1dir: Arvore

Gera as seguintes funções:

(make-arvore iD esq dir)
(arvore? a)
(Arvore-iD a)
(Arvore-esq a)
(Arvore-dir a)
